server:
  port: 10001
spring:
  application:
    name: server-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 7777
        dashboard: 127.0.0.1:8080
      web-context-unify: false
      #      程序启动时，流控规则是否立即注册到Sentinel，配置为true表示立即注册到Sentinel。
      eager: true

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          route-id-prefix: gateway-
# 配置抽样采集数据。
  sleuth:
    sampler:
#      表示Sleuth的采样百分比
      probability: 1.0
  zipkin:
#    ZipKin服务端的地址。
    base-url: http://127.0.0.1:9411
#    配置成false，使Nacos将其当成一个URL，不要按服务名处理。
    discovery-client-enabled: false